KP-778 [File System] Add feature to securely delete file
Kaholo/kaholo-plugin-fs pull request #15
Opened 2022-06-09 17:20 UTC by xkcm

[**KP-778 in Jira**](https://kaholo.atlassian.net/browse/KP-778)

2022-06-10 15:03 UTC, kenskyfish approved these changes, later dismissed

2022-06-10 15:42 UTC, kenskyfish approved these changes, later dismissed

2022-06-13 12:45 UTC, graddaniel requested changes

2022-06-13 12:45 UTC, graddaniel commented on app.js
> +  if (pathExists && securely) {
If doesn't exist then remove?

2022-06-13 12:58 UTC, xkcm commented on app.js
> +  if (pathExists && securely) {
`fs.remove()` will not throw an error if path does not exist, but if we try to shred a non-existent path it will throw an error, that's why this check is necessary here.

2022-06-14 07:17 UTC, graddaniel commented on app.js
> +  if (pathExists && securely) {
If it doesn't exist then there's no need to perform that operation. We shouldn't base our logic on the underlying framework/library.
Ask Kenny what should be the behavior in such situation - ignore, message or error, and add it in such case.

2022-06-14 13:52 UTC, kenskyfish approved these changes

2022-06-15 08:27 UTC, graddaniel approved these changes

2022-06-15 11:19 UTC, merged